# -*- coding: utf-8 -*-
"""Qevlar-SecOps-Tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFN0079Bc0LA1GiI30HWxWTrAYKBV3u_
"""



#Step 1-a
import requests

def get_threat_investigations():
    """
    Fetches investigations from the Qevlar TAM Case API
    and filters them where the verdict is 'Threat'.
    """
    url = "https://qevlar-tam-case-api-production.up.railway.app/investigations"

    # Passing the filter as a query parameter
    params = {
        "verdict": "Threat"
    }

    try:
        response = requests.get(url, params=params)

        # Raise an exception for HTTP errors (4xx, 5xx)
        response.raise_for_status()

        # Parse and return the JSON response
        investigations = response.json()
        return investigations

    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
    except requests.exceptions.ConnectionError as conn_err:
        print(f"Connection error occurred: {conn_err}")
    except requests.exceptions.Timeout as timeout_err:
        print(f"Timeout error occurred: {timeout_err}")
    except requests.exceptions.RequestException as req_err:
        print(f"An error occurred: {req_err}")

    return None

# Example usage:

# Step 1 B: Execution of Fetch Investigation
import json
if __name__ == "__main__":
    threats_data = get_threat_investigations()

    if threats_data and 'investigations' in threats_data:
        threats = threats_data['investigations']
        if threats:
            print(f"Successfully retrieved {len(threats)} threat investigation(s).")
            #Print the first item nicely if the list isn't empty
            if len(threats) > 0:
                print(json.dumps(threats[0], indent=4))
        else:
            print("No threat investigations found.")
    else:
        print("No data retrieved or an error occurred.")

"""### Step 2A: Send High Priority Investigations to Queue"""

import requests

def send_high_priority_investigations(investigations):
    """
    Sends investigations with confidence_score >= 0.8 to a high priority queue.
    """
    high_priority_url = "https://webhook.site/0ad55294-bf25-4732-b669-ba5a6442914e"
    sent_count = 0

    if not investigations:
        print("No investigations to process.")
        return

    print("Checking investigations for high priority...")
    for investigation in investigations:
        if investigation.get('confidence_score', 0) >= 0.8:
            try:
                print(f"Sending investigation {investigation.get('id', 'N/A')} to high priority queue...")
                response = requests.post(high_priority_url, json=investigation)
                response.raise_for_status()  # Raise an exception for HTTP errors
                print(f"Successfully sent investigation {investigation.get('id', 'N/A')}. Status Code: {response.status_code}")
                sent_count += 1
            except requests.exceptions.HTTPError as http_err:
                print(f"HTTP error for investigation {investigation.get('id', 'N/A')}: {http_err}")
            except requests.exceptions.ConnectionError as conn_err:
                print(f"Connection error for investigation {investigation.get('id', 'N/A')}: {conn_err}")
            except requests.exceptions.Timeout as timeout_err:
                print(f"Timeout error for investigation {investigation.get('id', 'N/A')}: {timeout_err}")
            except requests.exceptions.RequestException as req_err:
                print(f"An error occurred while sending investigation {investigation.get('id', 'N/A')}: {req_err}")

    if sent_count == 0:
        print("No high priority investigations found.")
    else:
        print(f"Finished. Sent {sent_count} high priority investigation(s).")

"""### Step 2B: Execute High Priority Queue Function"""

if __name__ == "__main__":
    # Assuming 'threats' list is available from the previous step (e.g., cell eTgNa5NbplTC)
    # Make sure 'threats' holds the list of investigation dictionaries.
    # If it's not directly available, you might need to re-run get_threat_investigations()
    # and extract the 'investigations' list again.
    if 'threats' in locals() and isinstance(threats, list):
        send_high_priority_investigations(threats)
    else:
        print("Error: 'threats' variable not found or is not a list. Please ensure previous steps ran successfully.")
        print("Attempting to re-fetch investigations...")
        re_fetched_data = get_threat_investigations()
        if re_fetched_data and 'investigations' in re_fetched_data:
            send_high_priority_investigations(re_fetched_data['investigations'])
        else:
            print("Failed to re-fetch investigations. Cannot send to high priority queue.")

"""### Step 2 C : Send Review Queue Investigations to Queue"""

import requests

def send_review_queue_investigations(investigations):
    """
    Sends investigations with confidence_score < 0.8 to a review queue.
    """
    review_queue_url = "https://webhook.site/ff306b9a-022b-402d-b966-12f336572576"
    sent_count = 0

    if not investigations:
        print("No investigations to process.")
        return

    print("Checking investigations for review queue...")
    for investigation in investigations:
        if investigation.get('confidence_score', 0) < 0.8:
            try:
                print(f"Sending investigation {investigation.get('id', 'N/A')} to review queue...")
                response = requests.post(review_queue_url, json=investigation)
                response.raise_for_status()  # Raise an exception for HTTP errors
                print(f"Successfully sent investigation {investigation.get('id', 'N/A')}. Status Code: {response.status_code}")
                sent_count += 1
            except requests.exceptions.HTTPError as http_err:
                print(f"HTTP error for investigation {investigation.get('id', 'N/A')}: {http_err}")
            except requests.exceptions.ConnectionError as conn_err:
                print(f"Connection error for investigation {investigation.get('id', 'N/A')}: {conn_err}")
            except requests.exceptions.Timeout as timeout_err:
                print(f"Timeout error for investigation {investigation.get('id', 'N/A')}: {timeout_err}")
            except requests.exceptions.RequestException as req_err:
                print(f"An error occurred while sending investigation {investigation.get('id', 'N/A')}: {req_err}")

    if sent_count == 0:
        print("No investigations for review queue found.")
    else:
        print(f"Finished. Sent {sent_count} investigation(s) to review queue.")

"""### Step 2D: Execute Review Queue Function"""

if __name__ == "__main__":
    # Assuming 'threats' list is available from previous steps
    if 'threats' in locals() and isinstance(threats, list):
        send_review_queue_investigations(threats)
    else:
        print("Error: 'threats' variable not found or is not a list. Please ensure previous steps ran successfully.")
        print("Attempting to re-fetch investigations...")
        re_fetched_data = get_threat_investigations()
        if re_fetched_data and 'investigations' in re_fetched_data:
            send_review_queue_investigations(re_fetched_data['investigations'])
        else:
            print("Failed to re-fetch investigations. Cannot send to review queue.")

"""### Step 3E: Post High Confidence Feedback to Qevlar API"""

import requests

def post_high_confidence_feedback(investigations):
    """
    Posts feedback for investigations with confidence_score >= 0.8 to the Qevlar feedback API.
    """
    feedback_url = "https://qevlar-tam-case-api-production.up.railway.app/feedback"
    feedback_count = 0

    if not investigations:
        print("No investigations to process for feedback.")
        return

    print("Checking investigations for high confidence feedback...")
    for investigation in investigations:
        if investigation.get('confidence_score', 0) >= 0.8:
            investigation_id = investigation.get('id', 'N/A')
            feedback_payload = {
                "investigation_id": investigation_id,
                "analyst_verdict": "true_positive",
                "comment": "Auto-confirmed high confidence"
            }
            try:
                print(f"Posting feedback for investigation {investigation_id}...")
                response = requests.post(feedback_url, json=feedback_payload)
                response.raise_for_status()  # Raise an exception for HTTP errors
                print(f"Successfully posted feedback for {investigation_id}. Status Code: {response.status_code}")
                feedback_count += 1
            except requests.exceptions.HTTPError as http_err:
                print(f"HTTP error for investigation {investigation_id}: {http_err}")
            except requests.exceptions.ConnectionError as conn_err:
                print(f"Connection error for investigation {investigation_id}: {conn_err}")
            except requests.exceptions.Timeout as timeout_err:
                print(f"Timeout error for investigation {investigation_id}: {timeout_err}")
            except requests.exceptions.RequestException as req_err:
                print(f"An error occurred while posting feedback for {investigation_id}: {req_err}")

    if feedback_count == 0:
        print("No high confidence investigations found to post feedback for.")
    else:
        print(f"Finished. Posted feedback for {feedback_count} high confidence investigation(s).")

"""### Step 3F: Execute High Confidence Feedback Function"""

if __name__ == "__main__":
    # Ensure 'threats' list is available from previous steps
    if 'threats' in locals() and isinstance(threats, list):
        post_high_confidence_feedback(threats)
    else:
        print("Error: 'threats' variable not found or is not a list. Please ensure previous steps ran successfully.")
        print("Attempting to re-fetch investigations...")
        re_fetched_data = get_threat_investigations()
        if re_fetched_data and 'investigations' in re_fetched_data:
            post_high_confidence_feedback(re_fetched_data['investigations'])
        else:
            print("Failed to re-fetch investigations. Cannot post high confidence feedback.")

